[style]
enable_sections = [
    "break",
    "build",
    "feat",
    "fix",
    "revert",
    "refactor",
    "perf",
]

[style.sections]
break = {attr = "breaking_changes", bool = true, name = "Breaking Changes"}
build = {attr = "type", regex = "build", name = "Build"}
ci = {attr = "type", regex = "ci", name = "CI"}
perf = {attr = "type", regex = "perf", name = "Performance Improvements"}
feat = {attr = "type", regex = "feat", name = "Features"}
fix = {attr = "type", regex = "fix", name = "Bug Fixes"}
revert = {attr = "type", regex = "revert", name = "Reverts"}
docs = {attr = "type", regex = "docs?", name = "Documentation"}
style = {attr = "type", regex = "style", name = "Style"}
refactor = {attr = "type", regex = "refactor", name = "Code Refactoring"}
test = {attr = "type", regex = "tests?", name = "Tests"}
chore = {attr = "type", regex = "chore", name = "Chore"}

[style.rules.subject]
regex = "^(?P<type>[a-z]+)(?:\\((?P<scope>.+)\\))?: (?P<subject>.+)$"

[style.rules.body]
[style.rules.breaking_changes]
regex = "^break(?:s|ing changes?)?:?\\s*(?P<breaking_changes>(?:.+\\n)*)"
multiline = true
find_all = true